version: '3.7'

networks:
  portfolio:
    driver: bridge

services:
  back-portfolio:
    build: 
      context: .
      dockerfile: ./.docker/config/Dockerfile
    entrypoint: sh ./.docker/entrypoint.sh
    environment:
      DATABASE_URL: postgresql://postgres:root_password@db-portfolio:5432/portfolio?schema=public
    container_name: back-portfolio
    tty: true
    volumes:
      - .:/usr/back-portfolio/app
    restart: on-failure
    ports:
      - 3000:3000
    networks:
      - portfolio
    depends_on:
      - db-portfolio
  db-portfolio:
    image: postgres
    restart: on-failure
    container_name: db-portfolio
    environment:
      POSTGRES_PASSWORD: root_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - portfolio